### ISSUE TITLE
Newlines are not passed to "notes"

### ISSUE THREAD

**Issue by ollitapa** [applivery/steps-applivery-ios-deploy#3]
When using nodes-android/ci-bitrise-changelog-step to generate a commit changelog like

```
 - Cleaned up the code (joso@nodes.dk - Wed, 24 May 2017 18:44:38 +0200)
 - Initial commit (joso@nodes.dk - Wed, 24 May 2017 10:32:34 +0200)
```
and passing this in an environment variable to applivery release "notes" newlines are stripped from the input and not sent to applivery. Like so:
``` 
- Cleaned up the code (joso@nodes.dk - Wed, 24 May 2017 18:44:38 +0200)- Initial commit (joso@nodes.dk - Wed, 24 May 2017 10:32:34 +0200)
```

I think this happens in the "curl" script...

**Comment by CesarTrigo** [comment]
Hi @ollitapa ! Thank you for opening the Issue.
Our team is investigating into it.
Best,
C.

**Comment by CesarTrigo** [comment]
Fixed in early 2020 with the release of the new API
